name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - qa
          - uat
          - prod

jobs:
  test:
    environment: ${{ inputs.env || 'dev' }}
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - name: Base64 encode the secret
      run: |
        echo "Encoded secret: $(echo -n "$MY_SECRET" | base64)"
      env:
        MY_SECRET: ${{ secrets.BASE_URL }}
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install yarn
      run: npm install --global yarn
    - name: Install dependencies
      run: yarn install --frozen-lockfile
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: ENV=${{ inputs.env || 'dev' }} npx playwright test --project ui
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
